### PR TITLE
Tab swiching logic

### PR DESCRIPTION
**Pull request by TheBigSteph**
This project is a simple restaurant homepage, menu page, and contact page generate using only javascript, webpack and npm do build this project.

### CODE REVIEW

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Nice page, well done!

It looks great and is coming into place, but we need to fix some issues before continuing:

* [ ] Enable Stickler on this repository.
* [ ] Add a short description to this Pull Request - you can edit your initial message to add a summary of the changes you made ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

Status: __Request changes__.

**Comment by TheBigSteph** [comment]
Screen Shot 2020-03-18 at 19 43 57
Hello @MauricioRobayo,
Like you can see, I enabled Stickler on this repository but I don't know why it doesn't appear here.

**Comment by MauricioRobayo** [comment]
> Hello @MauricioRobayo,
> Like you can see, I enabled Stickler on this repository but I don't know why it doesn't appear here.

Have you checked on https://stickler-ci.com/? There should be a list with your repos and the switch next to it should be turned on.

**Comment by azdrenymeri** [comment]
Hello @TheBigSteph  :wave: 
To enable the `stickler` on your repository follow the below setps:
1. visit https://stickler-ci.com/ and click Signup with GitHub
2. After giving permission for stickler to use your GitHub profile you should see a dashboard with all your repositories containing a switch on the left of each repository.
scr
scr

**Pull request closed without merging**
